export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST';
export const GET_ARTICLE_BY_ID = 'GET_ARTICLE_BY_ID';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const SHOW_BANNER = 'SHOW_BANNER';
export const FETCH_BANNER = 'FETCH_BANNER';
