export const FETCH_ALL_CHILD_CURRENCIES = 'fetch/ALL_CHILD_CURRENCIES';
export const FETCH_CHILD_CURRENCIES_AVAILABLE =
  'fetch/CHILD_CURRENCIES_AVAILABLE';
export const Upsert_CHILD_CURRENCIES = 'upsert/CHILD_CURRENCIES';
