export const FETCH_PAYPAL_DEPOSIT = "FETCH_PAYPAL_DEPOSIT";
export const FETCH_PAYPAL_WITHDRAW = "FETCH_PAYPAL_WITHDRAW";
export const ACCEPT_PAYPAL_DEPOSIT = "ACCEPT_PAYPAL_DEPOSIT";
export const CANCEL_PAYPAL_WITHDRAW = "CANCEL_PAYPAL_WITHDRAW";
